workflows:
  android-build:
    name: Build APK
    max_build_duration: 60

    environment:
      java: 17

    scripts:
      - chmod +x gradlew || true
      - ./gradlew assembleDebug

    artifacts:
      - app/build/outputs/**/*.apk
